services:
  postgres:
    image: postgres:15
    container_name: user-activity-tracking-go-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_activity_tracking_go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
