definitions:
  github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.PageMetadata:
    properties:
      page:
        type: integer
      size:
        type: integer
      total_item:
        type: integer
      total_page:
        type: integer
    type: object
  ? github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResGetClientDailyRequestCount
  : properties:
      data:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResGetClientDailyRequestCount'
      error_detail:
        items:
          type: string
        type: array
      error_message:
        type: string
      paging:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.PageMetadata'
    type: object
  ? github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResGetClientDetail
  : properties:
      data:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResGetClientDetail'
      error_detail:
        items:
          type: string
        type: array
      error_message:
        type: string
      paging:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.PageMetadata'
    type: object
  ? github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResGetTop3ClientRequestCount24Hour
  : properties:
      data:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResGetTop3ClientRequestCount24Hour'
      error_detail:
        items:
          type: string
        type: array
      error_message:
        type: string
      paging:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.PageMetadata'
    type: object
  ? github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResLogin
  : properties:
      data:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResLogin'
      error_detail:
        items:
          type: string
        type: array
      error_message:
        type: string
      paging:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.PageMetadata'
    type: object
  ? github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResRecordAPIHit
  : properties:
      data:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResRecordAPIHit'
      error_detail:
        items:
          type: string
        type: array
      error_message:
        type: string
      paging:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.PageMetadata'
    type: object
  ? github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResRegister
  : properties:
      data:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResRegister'
      error_detail:
        items:
          type: string
        type: array
      error_message:
        type: string
      paging:
        $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.PageMetadata'
    type: object
  github_com_Hidayathamir_user-activity-tracking-go_internal_model.DailyCount:
    properties:
      count:
        type: integer
      date:
        type: string
    type: object
  github_com_Hidayathamir_user-activity-tracking-go_internal_model.NameCount:
    properties:
      count:
        type: integer
      name:
        type: string
    type: object
  github_com_Hidayathamir_user-activity-tracking-go_internal_model.ReqLogin:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
  github_com_Hidayathamir_user-activity-tracking-go_internal_model.ReqRecordAPIHit:
    properties:
      api_key:
        type: string
      endpoint:
        type: string
      ip:
        type: string
      timestamp:
        format: date-time
        type: string
    required:
    - api_key
    - endpoint
    - ip
    - timestamp
    type: object
  github_com_Hidayathamir_user-activity-tracking-go_internal_model.ReqRegister:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResGetClientDailyRequestCount:
    properties:
      daily_count_list:
        items:
          $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_model.DailyCount'
        type: array
    type: object
  github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResGetClientDetail:
    properties:
      api_key:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResGetTop3ClientRequestCount24Hour:
    properties:
      name_count_list:
        items:
          $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_model.NameCount'
        type: array
    type: object
  github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResLogin:
    properties:
      token:
        type: string
    type: object
  github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResRecordAPIHit:
    properties:
      ok:
        type: boolean
    type: object
  github_com_Hidayathamir_user-activity-tracking-go_internal_model.ResRegister:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  title: User Activity Tracking Go
paths:
  /api/client/me:
    get:
      consumes:
      - application/json
      description: Get client detail
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResGetClientDetail'
      security:
      - ApiKeyJWTAuth: []
      summary: Get client detail
      tags:
      - Client
  /api/login:
    post:
      consumes:
      - application/json
      description: Login a client with name and password
      parameters:
      - description: Client Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_model.ReqLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResLogin'
      summary: Login a client
      tags:
      - Client
  /api/logs:
    post:
      consumes:
      - application/json
      description: Record api hit
      parameters:
      - description: Record API Hit Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_model.ReqRecordAPIHit'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResRecordAPIHit'
      security:
      - ApiKeyXInternalSecret: []
      summary: Record api hit
      tags:
      - RequestLog
  /api/register:
    post:
      consumes:
      - application/json
      description: Register a new client with name, email, and password
      parameters:
      - description: Client Registration Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_model.ReqRegister'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResRegister'
      summary: Register a new client
      tags:
      - Client
  /api/usage/daily:
    get:
      consumes:
      - application/json
      description: Get client daily request count
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResGetClientDailyRequestCount'
      security:
      - ApiKeyJWTAuth: []
      summary: Get client daily request count
      tags:
      - RequestLog
  /api/usage/top:
    get:
      consumes:
      - application/json
      description: Get top 3 client request count in last 24 hours
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Hidayathamir_user-activity-tracking-go_internal_delivery_http_response.WebResponse-github_com_Hidayathamir_user-activity-tracking-go_internal_model_ResGetTop3ClientRequestCount24Hour'
      security:
      - ApiKeyJWTAuth: []
      summary: Get top 3 client request count in last 24 hours
      tags:
      - RequestLog
securityDefinitions:
  ApiKeyJWTAuth:
    description: JWT authorization
    in: header
    name: Authorization
    type: apiKey
  ApiKeyXInternalSecret:
    description: X Internal Secret
    in: header
    name: X-Internal-Secret
    type: apiKey
swagger: "2.0"
